# Generated by Django 5.0.13 on 2025-03-15 08:08

import core.utils
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to=core.utils.get_student_photo_path)),
                ('student_address', models.TextField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('father_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_address', models.TextField(blank=True, null=True)),
                ('guardian_relationship', models.CharField(blank=True, choices=[('FATHER', 'Pai'), ('MOTHER', 'Mãe'), ('GRANDPARENT', 'Avô/Avó'), ('BROTHER', 'Irmão'), ('SISTER', 'Irmã'), ('UNCLE', 'Tio'), ('AUNT', 'Tia'), ('COUSIN', 'Primo'), ('OTHER', 'Outro')], max_length=20, null=True)),
                ('other_guardian_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
